### ISSUE TITLE
textVal is always Blank

### ISSUE THREAD

**Issue by jh-sigmadx** [sameerjkl/pcf_speechtotext#4]
I have added your PCF Component into my Environment, and added it to a Canvas App.
The Control seems to work fine - it asks my browser for permission to use the microphone, and then I can see it transcribing my speech.

However, I cannot store the captured text into a variable.

Setting a Label.Text = SpeechToText1.TextVal does not show the text
Using Set(str_Output,SpeechToText1.TextVal) does not work either - I have tried it both on the SpeechToText1.OnChange, and a separate Button control

The TextVal is ALWAYS an empty string ("" - not Blank)

I am on Canvas App Authoring Version 3.24064.21, but I have tried versions as far back as 3.24061.19 with no joy.
(I'm wondering if Microsoft changed something in the underlying Framework that stops the output properties from updating?)

Also - I was wondering how to trigger the control externally - you have a property called "TriggerVal", but no instructions on how to use it. 

Is it a True/False value like the Timer Control?
Or does it use any kind of changing Text like the PowerCat/Fluent UI components?

Thanks.
James.

**Comment by sameerjkl** [comment]
Hi James,

I apologise for not having the clear instructions on the PCF. Im so beginner with pcf control. This was my experiment. After power apps updates PCF output couldn’t get captured on the published version.

Im attaching the latest version on pcf with small instructions which may help you to capture the output.

[PowerAppsTools_pgpcf_1_7.zip](https://github.com/user-attachments/files/16159776/PowerAppsTools_pgpcf_1_7.zip)


Onchange of PCF set a variable. Set(varCapturedValue, Self.TextVal)

The text will always capture on stop icon press to the variable from onchange property

Please let me know in case you find any difficulties. I will capture a clear screen recording with proper instructions. Hope it helps

Regards,
Sameer Jakkali

[PowerAppsTools_pgpcf_1_7.zip](https://github.com/user-attachments/files/16159778/PowerAppsTools_pgpcf_1_7.zip)
